require:
  - rubocop-rspec
  - rubocop-rake
  - standard

inherit_gem:
  standard: config/ruby-3.0.yml

AllCops:
  NewCops: enable
  Exclude:
    - vendor/bundle/**/*

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/ExtraSpacing:
  Exclude:
    - "*.gemspec"

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
